### ISSUE TITLE
BiometricPromptApi28对cancel的监听存在问题

### ISSUE THREAD

**Issue by monkey000** [gaoyangcr7/BiometricPromptDemo#4]
按返回键取消时　并不会调用到onCancel()方法

**Comment by gaoyangcr7** [comment]
你什么手机？我找个手机试试

**Comment by monkey008** [comment]
> 你什么手机？我找个手机试试

最新的AOSP代码编译出的模拟器镜像

**Comment by gaoyangcr7** [comment]
看流程没问题，我就不太理解你说的onCancel是什么了。。。建议大家描述问题都描述清楚一点，思考半天没明白意思。。。

**Comment by gaoyangcr7** [comment]
能详细描述一下只的是哪个onCancel吗，现在有点懵

**Comment by monkey000** [comment]
`

        mButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                if (mManager.isBiometricPromptEnable()) {
                    mManager.authenticate(new BiometricPromptManager.OnBiometricIdentifyCallback() {
                        @Override
                        public void onUsePassword() {
                            Toast.makeText(MainActivity.this, "onUsePassword", Toast.LENGTH_SHORT).show();
                        }

                        @Override
                        public void onSucceeded() {

                            Toast.makeText(MainActivity.this, "onSucceeded", Toast.LENGTH_SHORT).show();
                        }

                        @Override
                        public void onFailed() {

                            Toast.makeText(MainActivity.this, "onFailed", Toast.LENGTH_SHORT).show();
                        }

                        @Override
                        public void onError(int code, String reason) {

                            Toast.makeText(MainActivity.this, "onError", Toast.LENGTH_SHORT).show();
                        }

                        @Override
                        public void onCancel() {

                            Toast.makeText(MainActivity.this, "onCancel", Toast.LENGTH_SHORT).show();
                        }
                    });
                }
            }
        });
`
MainActivity里设置的回调方法onCancel  在使用BiometricPromptApi28时不会被触发

**Comment by gaoyangcr7** [comment]
已修复，多谢反馈
